CONTAINER Osnowgen
{
    NAME Osnowgen;
    INCLUDE Obase;

    GROUP ID_OBJECTPROPERTIES
    {
        DEFAULT 4; COLUMNS 1;

        IN_EXCLUDE SNOWGEN_OBJS
        {
            NUM_FLAGS 1;
            INIT_STATE 1;
            SCALE_V;

            ACCEPT{Obase;}
        }
        
        SEPARATOR {} STATICTEXT {JOINEND;}

        LONG SNOWGEN_POINTS {CUSTOMGUI LONGSLIDER; MIN 0; MAXSLIDER 100; }
        REAL SNOWGEN_SIZE   {CUSTOMGUI REALSLIDER; MIN 0; MINSLIDER 1; MAXSLIDER 100;   UNIT METER;   }   
        LONG SNOWGEN_HULL   {CUSTOMGUI LONGSLIDER; MIN 0; MAX 100; MINSLIDER 0; MAXSLIDER 100;        } // Disable the limit
        
        REAL SNOWGEN_SEED   {MIN 1;}        
        
        SEPARATOR {LINE;}


    }
    
    GROUP SDS_GROUP
    {
        DEFAULT 1; COLUMNS 2;

        LONG SNOWGEN_MESH_MODE {CYCLE{SNOWGEN_MESH_MBALL; SNOWGEN_MESH_OVDB;} FIT_H;} STATICTEXT{JOINENDSCALE;} 

        SEPARATOR {} STATICTEXT {JOINEND;}

        LONG SNOWGEN_USE_SUB_T {CYCLE{SNOWGEN_USE_SUB_E; SNOWGEN_USE_SUB_R;} FIT_H;} STATICTEXT{JOINENDSCALE;} 

        SEPARATOR {} STATICTEXT {JOINEND;}

        REAL SNOWGEN_SDM_E  {MIN 1; UNIT METER;}

        REAL SNOWGEN_SDM_R  {MIN 1; UNIT METER;}

        LONG SNOWGEN_SDS_E  {MIN 0; MAX 6; }

        LONG SNOWGEN_SDS_R  {MIN 0; MAX 6; }
    }

}